from .cadastro import TelaCadastro
from .configuracoes import TelaConfiguracoes
from .importar_csv import TelaImportarCSV
from .inicio import TelaInicio
from .pessoas import TelaPessoas
from .registro_grupo import TelaRegistroGrupo
from .registro_individual import TelaRegistroIndividual
from .relatorios import TelaRelatorios
from .salas import TelaSalas
